version: '3.7'

services:
  nodejs:
    build: ./
    container_name: nodejs
    environment:
      - REACT_APP_TEST=TEST
      - REACT_APP_SERVER_IP=http://89.223.65.190:8000/
      - DISABLE_ESLINT_PLUGIN=true npm start
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro