version: '3.5'

services:
  node:
    build:
      context: './'
      dockerfile: 'Dockerfile-dev'
    environment:
      - REACT_APP_TEST=TEST
      - REACT_APP_SERVER_IP=${REACT_APP_SERVER_IP}
      - DISABLE_ESLINT_PLUGIN=true npm start
    ports:
      - 9573:3000
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
